### ISSUE TITLE
Auto-building package using GitLab

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rpm-spec-botan2#3]
@dewyatt I've just setup our GitLab repo to mirror this one.

https://gitlab.com/ribose/rpm-spec-botan2

Could you help setup the `.gitlab-ci.yml` file to automatically release the package? It's so much easier to use proper docker containers to release. Thanks!

**Comment by dewyatt** [comment]
@ronaldtse So first we'll need a GitHub OAuth token (at least one) for these automatic releases (same deal for either of Travis CI or GitLab CI). That token will need write access to the appropriate public repo(s) on GitHub for which we want to automate releases.

You can structure things a number of different ways, so there's a few decisions you'll want to make:
* Which GitHub account? You could globally use the `ribose-ci` account, for example (and add it to the appropriate teams) but you'll want to consider the implications of OAuth creds of a member of the `yum-upload` group being exposed (may not be a big deal since Ribose signs those RPMs). On the other end of the spectrum, you could create a GH machine user account for every repo that requires automatic releases. That could be a lot of maintenance though. Or you could come up with some middleground (let me know if you want ideas).
* Typically you'll want to store this in a GitLab group-level or project-level protected variable (depending on the above), conventionally something like `GITHUB_OAUTH_TOKEN`.

With that in place, specifically for this repo, on GitLab you'll want to:
1. Go to `Settings->Repository->Protected Branches`, and mark `master` as a protected branch. (protected variables will only be passed to protected branches/tags in GitLab CI).
2. Go to `Settings->CI / CD->General pipelines` and uncheck `Public pipelines`. This will disable CI job log viewing for the public, which is unfortunately necessary to limit the potential exposure of the OAuth token to the dev team (rather than *everyone*). Depending on how it is used, the token could end up being recorded in the job log. We can probably avoid that, but it's also trivial for a dev to inadvertently expose it via `CI_DEBUG_TRACE` and various other ways, so the safest bet is to keep job logs private.

EDIT:
More info if you're curious:
* https://docs.gitlab.com/ee/ci/pipelines.html#security-on-protected-branches
* https://docs.gitlab.com/ee/ci/variables/#priority-of-variables
* https://docs.gitlab.com/ee/ci/variables/#protected-variables
* https://docs.gitlab.com/ee/user/permissions.html#project-members-permissions

**Comment by dewyatt** [comment]
Also it may also be possible to further limit the OAuth token to a local machine that you maintain. You can probably register it as a runner with a specific tag and ensure that the deploy stage only ever runs on that runner (which would be the only runner with sensitive info defined in the environment). I think this would be similar to your current setup for the `yum` repo. Let me know if that sounds interesting and I can look into it further.

**Comment by ronaldtse** [comment]
@dewyatt Speaking of the GitHub OAuth token, I've been using a GitHub "Deploy Key" with success (for example, https://github.com/riboseinc/ogc-tcpnp). The benefit is a Deploy Key is per-repository, where the GitHub account approach is more complex to manage.

The Deploy Key is basically just an SSH key (see how it works here: https://github.com/riboseinc/ogc-tcpnp/blob/master/deploy.sh) that you generate yourself.

While in the example Travis is used to encrypt the `deploy_key` to `deploy_key.enc`, in GitLab we can insert the deploy key into the GitLab environment as a "protected variable".

Please help proceed with this approach; ping me if there are any questions on this flow!

**Comment by dewyatt** [comment]
@ronaldtse Unfortunately, AFAIK deploy keys do not enable any interaction with the GitHub API, which is what we'll need.

**Comment by ronaldtse** [comment]
But what interaction do we need with GitHub API? Publishing to our yum repo is purely a git push. I must be missing something...

**Comment by dewyatt** [comment]
Ok I think you've had a different strategy in mind than my own. Your idea is, for example, to automatically build the botan2 RPM and push to the `riboseinc:yum` repo?
I have been talking about doing automatic GitHub Releases of RPMs/other binaries. I've been playing with this in [dewyatt/gitlab-ci-releases-test](https://github.com/dewyatt/gitlab-ci-releases-test), see the result [here](https://github.com/dewyatt/gitlab-ci-releases-test/releases/tag/v0.11.16) (in this case `v0.11.16.txt` is the "binary" asset created in gitlab ci).

**Comment by ronaldtse** [comment]
Aha. That works. Just tell me what I need to do at my end. We do want to also have a copy of the RPM in the repo so they can be `yum install`-ed easily.

**Comment by dewyatt** [comment]
As far as the `yum` repo, I'm not sure it can be automated in CI without security compromises, since those are signed by the private Ribose Packaging key, right? (I don't know much about this, I'm assuming you have a closely-guarded local machine that does this with jenkins or something)

(EDIT: Also I do totally agree that they need to end up in the yum repo for usability.)

**Comment by ronaldtse** [comment]
We do currently use a private Jenkins instance to guard the packaging key. However, this setup hampers our open-source approach. In addition, the current approach does not solve build security for the future anyway because we will be also auto-releasing through the GitHub API.

It should be feasible to use an encrypted signing key that will be used to sign the packages on demand. The resulting packages obviously will rely on the security of the CI system. Need to think this through.

Let's try making it work first.

**Comment by dewyatt** [comment]
Another option would be to continue to maintain a local Ribose machine to run a specific protected runner, which would be the only place where secret data lives. We could tag certain jobs to only run on that runner. So, for example, a "deploy" or "release" job would only run on that machine, which would have the secret data in an environment variable. That way all the scripts/etc are open, just the environment variables are not.

Still thinking it through, but thought I would throw it out there. One thing at a time though, I'm getting ahead of myself here.

**Comment by ronaldtse** [comment]
Happy new year everyone! Following up on this it would be most effective to use a new packaging key that is intended for this purpose. By storing the private key on GitLab there will be a security risk, but we can deal with that as we go. @dewyatt could you help proceed with this? Thanks!

**Comment by dewyatt** [comment]
Sounds like a plan, working on it now.

**Comment by dewyatt** [comment]
@ronaldtse If you create the protected `GITHUB_API_TOKEN` variable and re-run https://gitlab.com/ribose/rpm-spec-botan2/-/jobs/142375415 then you should end up with a release here: https://github.com/riboseinc/rpm-spec-botan2/releases.
The token won't appear in the job log since it's pulled from the environment in `create-github-release.rb`.

**Comment by ronaldtse** [comment]
@dewyatt I've added the token to "Environment" in this page (https://gitlab.com/ribose/rpm-spec-botan2/settings/ci_cd), but seems that it's not getting read. Any tips?

**Comment by dewyatt** [comment]
@ronaldtse It looks to me like it's actually being read but doesn't have the proper permissions (note how the error is different from before...github often gives a 404 for this sort of thing).

I'm not sure if I mentioned it, but the only required OAuth scope for the token is "repo -> public_repo". Can you make sure that is checked and that the account (whatever account holds that token) has write permissions to this github repo?
(I think github organizations might have more granular permissions here so let me know if you don't see "public_repo" under the "repo" section).

**Comment by dewyatt** [comment]
Here is what it looks like from my perspective:
[GitHub](https://drive.google.com/file/d/1-2-IfGQRNAV0VYEINEGG7p01sxqqx8iV/view?usp=sharing)
[GitLab](https://drive.google.com/file/d/1H1CZ3d-OFAhHcmjAiszhvuS3xubmmZN1/view?usp=sharing)

**Comment by ronaldtse** [comment]
Wow it worked! I forgot to setup the GitHub permissions for this repo...

@dewyatt can we apply the same mechanism for all our other rpm-specs-* repos?

**Comment by dewyatt** [comment]
> @dewyatt can we apply the same mechanism for all our other rpm-specs-* repos?

Sure, I figured this repo would serve as a good test and then we could expand.
Quick questions:
1. Package signing. Do you want the GitHub Release-published RPMS to be signed?
2. Updating the [riboseinc:yum](https://github.com/riboseinc/yum) repo. Do you want this to be automated with a deploy key (incl. signing)? (I could try to reuse [riboseinc:packaging](https://github.com/riboseinc/packaging) but I haven't looked at that yet)
3. Or should I just skip the above for now and implement what we have here for the other RPM repos?

**Comment by ronaldtse** [comment]
@dewyatt Yes to all. But is it easier to finish 3 first before 1 and 2?

**Comment by dewyatt** [comment]
@ronaldtse Sorry about the slow response, yes that may make sense, I'll start looking at how to accomplish 3 now.

**Comment by dewyatt** [comment]
@ronaldtse Do you want the other rpm-specs-* repos to do GitHub Releases via GitLab CI, like this one? If so, you'll need to mirror those into gitlab, same as this one (I tried but don't have permission).

**Comment by dewyatt** [comment]
Also, I just got a notification from GitLab "You have been granted Owner access to the riboseinc group." (not the `ribose` group), which I found confusing so I just re-ownered it to you. I'm not sure, maybe I created that group when testing this stuff out? I really can't remember but either way it makes sense for you to maintain control of it (to avoid any impersonators, name squatters, etc).

**Comment by ronaldtse** [comment]
@dewyatt thanks for that, it would definitely keep off name squatters 😉

**Comment by ronaldtse** [comment]
Since I'm actually getting on the plane now, let me delegate this 😝 

> If so, you'll need to mirror those into gitlab, same as this one (I tried but don't have permission).

@ribose-jeffreylau could you please help perform this task? Thanks!

**Comment by dewyatt** [comment]
Jeffrey, if you haven't done it before, I think the quickest way is:
1. Go to gitlab.com
2. Click the "New project" button
3. Select the "CI/CD for external repo" tab
4. Click the "GitHub" button under "Connect repositories from"
5. Select the "ribose" group for the middle column ("To GitLab") on the appropriate repo
6. Click "Connect"

I also see a "Connect all repositories" option, so that might be useful if you don't want to do this for each of the 20+ rpm-spec-* repos (not sure if that would mirror private stuff that you don't want mirrored though).

**Comment by ribose-jeffreylau** [comment]
@dewyatt Thanks for the tips!  I've just connected all of rpm-spec-* repos using your method, except for `rpm-spec-botan2` which I previously imported some other way (forgotten which).

**Comment by dewyatt** [comment]
Excellent, thanks @ribose-jeffreylau !

**Comment by ronaldtse** [comment]
Thanks guys!

**Comment by dewyatt** [comment]
@ronaldtse So my efforts to expand this thus far are:
Base:
* https://github.com/riboseinc/rpm-specs/commit/3e6ba996a782f0ab8bc615a4dddb5a060a2d8d77 (template used by others)

Packages:
* https://github.com/riboseinc/rpm-spec-botan2/pull/5
* https://github.com/riboseinc/rpm-spec-automake116/pull/1
* https://github.com/riboseinc/rpm-spec-libgsf/pull/1
* https://github.com/riboseinc/rpm-spec-parallel/pull/1

Once the package PRs are merged, they should automatically create GitHub Releases. You can also view the artifacts prior to merge, like: https://gitlab.com/ribose/rpm-spec-automake116/-/jobs/160313016/artifacts/browse

@ribose-jeffreylau For some reason, this is the only repo that is not showing the GitLab CI pipeline in the PR (#5). I'm wondering if deleting this repo on GitLab and re-creating it the way the others were done (in https://github.com/riboseinc/rpm-spec-botan2/issues/3#issuecomment-457696154) would be a quick fix?

**Comment by ribose-jeffreylau** [comment]
Hi @dewyatt , I'll try deleting and re-creating it on GitLab to see if it fixes it.  Thanks!

**Comment by ribose-jeffreylau** [comment]
@dewyatt Actually, I don't seem to have the necessary permissions to delete the project on GitLab.

I'm wondering if https://gitlab.com/ribose/rpm-spec-botan2/pipelines/47214155 was started manually by @ronaldtse ?

**Comment by ronaldtse** [comment]
@ribose-jeffreylau should I go ahead to delete it? I'm not sure how it was created differently...

**Comment by ribose-jeffreylau** [comment]
@ronaldtse Yes, please delete it.  This repo was created manually by me, IIRC.

**Comment by ronaldtse** [comment]
@ribose-jeffreylau `rpm-spec-botan2` has been deleted on GitLab.

**Comment by ribose-jeffreylau** [comment]
Thanks @ronaldtse .  It has been recreated using the "connect" method.  Let's see how it goes.

**Comment by ronaldtse** [comment]
Thanks @ribose-jeffreylau !

**Comment by dewyatt** [comment]
It looks like that did the trick, I just had to do a push to kick CI
